#!/usr/bin/env node
// Builds docs/agent.md, the Glass text reference agents read, from schema/roles.json and the type measures, so roles,
// fields and limits in the docs can't drift from what the server enforces. Keep it short: it may be loaded into
// every agent session (the interface study found the rules, not the format, are what cost context).
//   node glass/scripts/guide.mjs           write docs/agent.md
//   node glass/scripts/guide.mjs --check   exit 1 if docs/agent.md is out of date
import fs from 'node:fs';
import { limitsFor } from '../js/content.mjs';
import { fieldsFor, META } from '../js/text.mjs';

const dir = new URL('..', import.meta.url).pathname;
const read = (f) => JSON.parse(fs.readFileSync(dir + f, 'utf8'));

export function build(schema = read('schema/roles.json'), measure = read('tokens/tokens.resolved.json').measure) {
  const chars = (l) => (measure[l.measure] || 40) * (l.lines || 1);
  const limit = (name, l) => {
    if (l === true) return name === 'progress' ? 'progress: 0-100' : `${name}: …`;
    if (name === 'title') return `title ${l.words ? `${l.words} words / ` : ''}${chars(l)} chars`;
    if (name === 'items') return `≤ ${l.max} items × ${chars(l)} chars`;
    return `${name} ${chars(l)} chars`;
  };
  const describe = (l, fields) => [...['title', 'body', 'items'].filter((f) => l[f]), ...fields].map((f) => limit(f, l[f])).join(' · ');
  const CHART = ['chart', 'data', 'labels', 'series', 'unit']; // explained in their own paragraph
  const extras = (role) => fieldsFor(schema, role).filter((f) => !META.includes(f) && !CHART.includes(f));
  const roleNames = Object.keys(schema.roles).filter((r) => !schema.roles[r].ambient);
  const ambient = Object.keys(schema.roles).filter((r) => schema.roles[r].ambient);
  const cardRoles = roleNames.filter((role) => !schema.roles[role].limits); // roles on the default limits
  const card = cardRoles.length ? describe(schema.defaults.limits, extras(cardRoles[0])) : '';
  const rows = roleNames.map((role) => {
    const own = schema.roles[role].limits;
    return `| ${role} | ${schema.roles[role].purpose} | ${own ? describe(own, extras(role)) : 'card fields'} |`;
  });

  return `<!-- Generated by glass/scripts/guide.mjs from schema/roles.json and the type measures. Don't edit by hand. -->
# Glass text

Write updates as plain-text blocks. A block starts with \`role: title\`; the lines under it are:
- \`- item\`, or task steps \`x done\` and \`> current\`
- \`field: value\` for the role's other fields (table), and \`ttl: 10m\` on any role
- any other line: the body

\`clear: role\` removes a role (\`clear: task, info\`, \`clear: all\`). A new \`role:\` line starts a new block.

| role | for | fields |
|---|---|---|
${rows.join('\n')}
${card ? `\nCard fields: ${card}.\n` : ''}${ambient.length ? `\n${ambient.length > 1 ? `${ambient.slice(0, -1).join(', ')} and ${ambient.at(-1)}` : ambient[0]} ${ambient.length > 1 ? 'are' : 'is'} kept up by provider scripts: don't write ${ambient.length > 1 ? 'them' : 'it'}.\n` : ''}
${fieldsFor(schema, cardRoles[0] || '').includes('chart') ? `Charts on a card: \`chart: line\` (trend) or \`chart: bars\` (≤ 7 to compare), \`data: 3 5 4 8\` (a second,
context series after \`|\`), optional \`labels: Mon, Tue\`, \`series: Name, Other\`, \`unit: W\`. The title still says the point.

` : ''}Writing:
- The title is the message, because most glances read only the title: "Train at 07:42", not "Train times".
- Put figures first. One fact per item, no full stops. Plain text only, no markdown or emoji.
- Text over a limit is cut at a word boundary.
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = build(), file = dir + 'docs/agent.md';
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (cur !== out) { console.error('docs/agent.md is out of date: run node glass/scripts/guide.mjs'); process.exit(1); }
    console.log('docs/agent.md is up to date');
  } else { fs.writeFileSync(file, out); console.log(`wrote docs/agent.md (${out.length} chars)`); }
}
