#!/usr/bin/env node
// Build css/tokens.css from tokens/tokens.json. Type sizes come from viewing distance and pixel pitch (principles §4).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const tokens = JSON.parse(fs.readFileSync(path.join(ROOT, 'tokens/tokens.json'), 'utf8'));

// Font size (px) whose cap height subtends `arcmin` at `distanceM`.
export function sizeFor(distanceM, arcmin, { pixelPitchMm, capHeightRatio } = tokens.inputs) {
  const capMm = distanceM * 1000 * Math.tan((arcmin / 60) * Math.PI / 180);
  return Math.ceil(capMm / capHeightRatio / pixelPitchMm);
}

// Distance (m) at which a font size reaches `arcmin`.
export function reachOf(px, arcmin, { pixelPitchMm, capHeightRatio } = tokens.inputs) {
  return (px * pixelPitchMm * capHeightRatio) / Math.tan((arcmin / 60) * Math.PI / 180) / 1000;
}

export function typeScale() {
  return Object.fromEntries(Object.entries(tokens.type).map(([k, t]) => [k, { ...t, px: t.px ?? sizeFor(t.distanceM, t.arcmin) }]));
}

// Characters that fit on one line of a component, from its type size and available width.
// Widths: full = panel minus gutters; card = full minus the card's hairline indent; item = card minus the list marker.
export function measures(scale = typeScale()) {
  const i = tokens.inputs, px = (v) => parseFloat(v);
  const full = i.panelWidthPx - 2 * px(tokens.space.gutter), card = full - px(tokens.space['card-indent']), item = card - px(tokens.space.marker);
  const per = (width, t) => Math.floor(width / (scale[t].px * i.avgCharEm));
  return { title: per(card, 'title'), body: per(card, 'body'), item: per(item, 'body'), notice: per(full, 'title'), alert: per(full, 'room'), alertBody: per(full, 'title') };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const scale = typeScale();
  const lines = ['/* Generated by glass/scripts/tokens.mjs from tokens/tokens.json. Do not edit by hand. */', ':root {'];
  const i = tokens.inputs;
  lines.push(`  /* inputs: pitch ${i.pixelPitchMm}mm, cap ${i.capHeightRatio}em, room ${i.distanceRoomM}m, near ${i.distanceNearM}m */`);
  for (const [k, t] of Object.entries(scale)) {
    const why = t.distanceM ? ` /* ${t.use}: ${t.arcmin}′ at ${t.distanceM} m */` : ` /* ${t.use} */`;
    lines.push(`  --gl-text-${k}: ${t.px}px;${why}`, `  --gl-weight-${k}: ${t.weight};`);
  }
  for (const [k, v] of Object.entries(tokens.ink)) lines.push(`  --gl-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.space)) lines.push(`  --gl-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.motion)) lines.push(`  --gl-${k}: ${v};`);
  lines.push('}', '');
  fs.writeFileSync(path.join(ROOT, 'css/tokens.css'), lines.join('\n'));
  fs.writeFileSync(path.join(ROOT, 'tokens/tokens.resolved.json'), JSON.stringify({ ...tokens, type: scale, measure: measures(scale) }, null, 2) + '\n');
  console.log('measure (chars/line):', JSON.stringify(measures(scale)));
  for (const [k, t] of Object.entries(scale)) console.log(`${k.padEnd(8)} ${String(t.px).padStart(4)}px  ${t.tier.padEnd(5)}  readable to ${reachOf(t.px, 20).toFixed(2)} m (20′)`);
}
